const onomatopoeia = [
    'aaht aahht bloooot',
    'aaugh',
    'abracadabra',
    'achoo',
    'ah',
    'ah uh ah uh',
    'ah - choo',
    'Ah - ooh - ga aha',
    'ahahah',
    'ahem',
    'ahh ha ha',
    'ahhhh',
    'ahoy',
    'Arf argh',
    'argh',
    'aroo',
    'aroo',
    'atishoo',
    'aw',
    'awk',
    'Baa',
    'babble',
    'babbler',
    'badaboom',
    'badonkadonk',
    'badum tish',
    'bah',
    'bam',
    'bamf',
    'bang',
    'baraag',
    'barf',
    'bark',
    'baroom',
    'bash',
    'bashed',
    'bashing',
    'batabatabata',
    'bawl',
    'bawled',
    'bawling',
    'bay',
    'beep',
    'belch',
    'bellbird',
    'bellow',
    'Biff',
    'bing',
    'blab',
    'blab / blabber',
    'blabbed',
    'blabbing',
    'blah',
    'blam',
    'blang',
    'blare blared',
    'blaring',
    'blast',
    'bleat',
    'bleep',
    'bling',
    'bling bling',
    'blip',
    'blub',
    'blubber',
    'blurp',
    'blurt',
    'blurted',
    'blurting',
    'bob - white',
    'bobolink',
    'boff',
    'boing',
    'boink',
    'bomb',
    'bomp / bop',
    'bong',
    'bong / dong',
    'bonk',
    'bonked',
    'bonking',
    'boo',
    'boo - hoo',
    'boom',
    'boooOOOOOOooo',
    'Boosh',
    'bray',
    'brouhaha',
    'brring',
    'Brrr',
    'brum - brum - brum',
    'bubble',
    'bubbled',
    'buck',
    'buffet',
    'buffoon',
    'bumble',
    'bumblebee',
    'bump',
    'burble',
    'burp',
    'burr',
    'buzz',
    'buzzed',
    'buzzing',
    'bwahaha!',
    'bwak',
    'bwak / bwok',
    'bweee',
    'bzzz',
    'ca - chunk',
    'cackle',
    'carambah',
    'caterwaul', 'caw',
    'cha - cha(-cha)',
    'cha - ching',
    'chachalaca',
    'chant',
    'chat',
    'chatter',
    'chatterer',
    'chattering',
    'cheep',
    'chickadee',
    'chiffchaff',
    'chiming',
    'chink',
    'chirp',
    'chirr',
    'chirrup',
    'chit',
    'chit - chat',
    'chitchat',
    'chitter',
    'chomp',
    'choo',
    'choo - choo',
    'chortle',
    'chough',
    'chukar',
    'chump',
    'chunk',
    'clack',
    'clacked',
    'clackety - clack',
    'clang',
    'clanged',
    'clanging',
    'clank',
    'clanked',
    'clanking',
    'clap',
    'clapped',
    'clapping',
    'claque',
    'clash',
    'clatter',
    'clattered',
    'clattering',
    'cliche',
    'click',
    'clickety - clack',
    'clink',
    'clinker',
    'clinking',
    'clip clop',
    'clobber',
    'clop',
    'clout',
    'cltkty cluck',
    'clucking',
    'clunk',
    'cock - a - doodle -doo ',
    'cough',
    'crack',
    'crackle',
    'crackling',
    'crash',
    'crashed',
    'creak',
    'creaked',
    'creaking',
    'Creek',
    'cricket',
    'crinkle',
    'crinkled',
    'crisp',
    'croak',
    'croaked',
    'croaker',
    'croon',
    'croup',
    'crow',
    'crumple',
    'crunch',
    'crunch, crunch, crunch',
    'crunchy',
    'cry',
    'cuckcoo',
    'cuckoo',
    'curlew',
    'currawong',
    'd’ oh / doh',
    'dab',
    'dada',
    'dakka',
    'dash',
    'deed - a - reedle',
    'dibble dibble dopp dopp',
    'didgeridoo',
    'dikdik ding',
    'ding - dong',
    'dirnt',
    'doink',
    'dong',
    'dong / bong',
    'doo - wop',
    'dook',
    'dook',
    'dot a dot dot drip',
    'drizzle',
    'drone',
    'drop',
    'drum',
    'drumming',
    'dubdubdubdubdubdub',
    'duh',
    'dwoiiinnnnnnnngggg',
    'echo',
    'eee - aaaah',
    'eeeeeee',
    'eek eek',
    'eew',
    'eeyore',
    'eh',
    'fa - thud',
    'fanfare',
    'fart',
    'fash',
    'Ffffffffffffff',
    'fillip',
    'finch',
    'fisst',
    'fizz',
    'fizz / fizzle',
    'fizzed',
    'fizzle fizzled',
    'flac - flac - flac',
    'flap',
    'flapped',
    'flash',
    'flatulence',
    'flibbertigibbet',
    'flick',
    'flick a flack fleck',
    'Fling',
    'flip flip - flop',
    'flop',
    'flump',
    'flumppf',
    'flush',
    'flutter',
    'fluttered',
    'Fnarr!Fnarr!',
    'freh, freh, freh',
    'frou - frou',
    'gabing',
    'gada, gada, gada',
    'gag',
    'gaggle',
    'gak',
    'gak',
    'gallop',
    'gargle',
    'gargled',
    'gasp',
    'gecko',
    'gibber',
    'gibber(ish)',
    'giggle',
    'glok / klok',
    'gloop',
    'glop',
    'glub glug',
    'glup',
    'gnash',
    'gnaw',
    'gobble',
    'gobbled',
    'gong',
    'grind',
    'groan',
    'groaned',
    'growl',
    'growling',
    'growls',
    'grr',
    'grumble',
    'grumbling grump',
    'grumph',
    'grunt',
    'grunted',
    'guffaw',
    'gulped',
    'gunko, gunko',
    'gurgle',
    'gurgled',
    'gurgling',
    'gurrhr',
    'gush',
    'gushed',
    'gwuf, gwuf, gwuf',
    'gyuh gyuh, gyuh',
    'haha!',
    'ha - ha - ha - HA ',
    'ha!',
    'ha.',
    'hack',
    'hackigi - gi - gi ',
    'hah!',
    'haha',
    'har har!',
    'harumph',
    'haw',
    'he - he',
    'hee haw',
    'hee!/ heeheehee!',
    'heh, heh!',
    'hehehe!',
    'hem / ahem',
    'hey',
    'hiccups',
    'hip',
    'hiss',
    'hissed',
    'ho',
    'ho ho ho!',
    'ho hum',
    'hock',
    'holler',
    'honk',
    'hoo hoo',
    'hoo hoo hoo hoo',
    'hoopoe',
    'hooray / hurrah',
    'hoot',
    'hooted',
    'hottentot',
    'houyhnhnm',
    'howl',
    'howled',
    'howler monkey',
    'hrrooonnh',
    'hubbub',
    'huff',
    'huh',
    'huh huh huh',
    'hum',
    'humbug',
    'hummed',
    'humming',
    'hummingbird',
    'humph',
    'hurrah',
    'hurrah / hooray',
    'hush',
    'huuuooohar',
    'huuuuuuuuuugh',
    'hyuk hyuk',
    'icky',
    'itch',
    'jabber',
    'jangle',
    'jar jee je je jeee',
    'jingle jug',
    'jump',
    'ka - ching',
    'Kaaahhkkk',
    'kaaapooooom',
    'kaboom',
    'kapow',
    'kapow',
    'kashl',
    'kata - kata',
    'katydid',
    'kea',
    'kekekeke',
    'ker - ching kerplunk ',
    'killdeer',
    'kirik',
    'kish - kish',
    'kite',
    'kittiwake',
    'klam',
    'klok, glok',
    'klopp klopp klopp',
    'klunk',
    'knack knell',
    'knock',
    'knock - knock',
    'knocking',
    'knot',
    'koink',
    'kong',
    'kra, ka, ka, hi',
    'Krrrrrrrr',
    'kut - kut - kut',
    'kwok',
    'la',
    'lap',
    'lash laugh',
    'laughing',
    'lilt lisp',
    'low',
    'meow',
    'meowing',
    'mew',
    'miaow',
    'mmm',
    'moan',
    'moaned',
    'moaning moo',
    'moob',
    'mooed',
    'mopoke',
    'morepork',
    'mrow',
    'mrrrrgggggllll',
    'mum',
    'mumble mumbled',
    'munch',
    'murmer',
    'murmur',
    'murmured',
    'mutter',
    'muuhhhrrr',
    'mwahaha / mwahaha /muahaha',
    'na na, na NA na',
    'naa',
    'natter',
    'NEE - eu NEE - eu , neener, neener',
    'neigh',
    'neow',
    'Nibble nnneeaoowww',
    'nnnghuh nnnguh',
    'northern flicker',
    'nyah, nyah / nya, ',
    'oink',
    'oinked',
    'om nom nom',
    'oo oo oo',
    'ooh ook',
    'oompah',
    'oonse',
    'oontz',
    'oooaughoaua oops',
    'ooze',
    'ouch',
    'Ow',
    'owooooah',
    'p - taff',
    'pad',
    'pah - pa - rah',
    'pant',
    'parp',
    'pat',
    'patter',
    'pattered',
    'pee - oo - wee',
    'peep',
    'peeper',
    'pew pew',
    'pewee / peewee',
    'pewit / peewit',
    'phew',
    'phooey',
    'pht / ft',
    'piaaaak',
    'pickle - pee pied currawong',
    'ping',
    'ping - pong',
    'pip',
    'pitter - patter',
    'plain chachalaca',
    'plink',
    'Plip– plip– ploop– plip– plip– plip– plip– ploop',
    'plonk',
    'plop',
    'plopped',
    'plopping',
    'pluck',
    'plump',
    'plunk',
    'Poke',
    'poof',
    'poomb',
    'poop pop',
    'popped',
    'popping',
    'potato - potato -potato',
    'pow',
    'prattle',
    'prrr / purr',
    'psst',
    'ptooey',
    'puff',
    'puh - puh - puh',
    'puhVRooPuhHoo puhV',
    'puke',
    'pump',
    'pump - a - rum',
    'punt',
    'purr',
    'purr / prr',
    'purred',
    'quack',
    'quacked quacking',
    'quiver',
    'rabble',
    'racket',
    'rail',
    'rap',
    'raspberry',
    'raspy',
    'rataplan',
    'ratatatat / rat - ',
    'ratchet',
    'rattle',
    'rattled',
    'rattlesnake',
    'rawr',
    'red knot reek',
    'regurgitate',
    'revved',
    'ribbit',
    'ribbit',
    'ring',
    'ringing',
    'rinky - dink',
    'rip',
    'ripped',
    'rizzz',
    'roar',
    'roared',
    'roaring rooaaarrr',
    'rowr',
    'rrrinngg',
    'rrrruuuurrrr',
    'rub - a - dub',
    'ruff',
    'rumble',
    'rumbled',
    'rump - rump',
    'rush',
    'rustle',
    'rustled',
    'rustling',
    'scat',
    'schhwaff',
    'Schklikt, klikt',
    'schlikt',
    'schlip',
    'schreech',
    'schwump schwump',
    'scratch',
    'screech',
    'screeched',
    'screeching',
    'scritch',
    'scrunch',
    'shashing',
    'shatter',
    'shazam',
    'sheesh',
    'Shh',
    'shiiiiing',
    'shiiin',
    'shines',
    'shiver',
    'shock',
    'shoo',
    'shoop',
    'shoosh',
    'shriek',
    'shrieked',
    'shudder',
    'shuffle',
    'shuffle, shuffle, ',
    'shuh, shuh, shuh',
    'shush',
    'shuush, shuush',
    'shwap',
    'sigh',
    'sings',
    'siss',
    'sizzle',
    'sizzled',
    'sizzling',
    'skirl',
    'skraaa',
    'skraww',
    'skreek skrrreeek',
    'slam',
    'slap',
    'slash',
    'slashed',
    'slip',
    'slither',
    'slobber',
    'slop',
    'slosh',
    'slump',
    'slurp',
    'slurped',
    'slurping',
    'smack',
    'smacked',
    'smash',
    'smashed',
    'smooch',
    'smooth',
    'snap',
    'snapped',
    'snarl',
    'sneeze',
    'snick',
    'snicker',
    'sniff',
    'sniffed',
    'sniffle / snuffle',
    'snikt',
    'snip',
    'snore',
    'snort',
    'snorted',
    'snuffle',
    'sob',
    'sock',
    'sora',
    'spack a speck spec',
    'spank',
    'spark',
    'Sparkle',
    'spit',
    'splash',
    'splashed splat',
    'splatt',
    'splatter',
    'splattered',
    'splish',
    'splosh',
    'splosh / sploosh',
    'splut',
    'splutter',
    'spoing',
    'spoot',
    'spray',
    'sprayed',
    'sprinkle',
    'sputter',
    'squabble',
    'squall',
    'squashed',
    'squawk',
    'squeak',
    'squeal',
    'squealed',
    'squealing',
    'squelch',
    'squirt',
    'squish',
    'squished',
    'ssinda, sssssinda',
    'sssshblamm',
    'static',
    'stomp',
    'strident',
    'strum',
    'stup',
    'suru suru',
    'susurration',
    'swah / shwah',
    'swash',
    'swat',
    'sweep',
    'swish',
    'switch',
    'swoop',
    'swoosh',
    'swooshed',
    't’ chi',
    'ta - da / ta - dah',
    'tack, tack, tack /',
    'takka takka',
    'tap',
    'tapped',
    'tattle',
    'tch, tch, tch',
    'teehee!',
    'terwit terwoo',
    'thisshig rrrerrk',
    'thith - thith - th',
    'throb',
    'throbbing',
    'thrum',
    'thubalup',
    'thud',
    'thump',
    'thumped',
    'thunder',
    'thung',
    'thunk',
    'thunk',
    'thwack thwip',
    'thwogg / thwok',
    'thwok',
    'tick',
    'tick tock / tic to',
    'tick - tock',
    'ticking',
    'ting',
    'tinkle',
    'tinkling',
    'tintinnabulation',
    'tiptoe',
    'titter',
    'tk.tk.tk.tk.tk.tk',
    'tlick',
    'tlot',
    'tlot tlot',
    'tocotocotoco',
    'toink',
    'tolling',
    'tom - tom',
    'tong',
    'toot',
    'tootle - too tremb',
    'trickle',
    'trickled',
    'trill',
    'trumpet',
    'trumpeter',
    'tsk',
    'tu - whu',
    'tuckaTHUCKtuckaTHU',
    'tuff',
    'tug',
    'tuk - tuk',
    'tup',
    'Tut - tut',
    'twang',
    'tweet',
    'tweeted',
    'tweeter',
    'twiddle',
    'twinkle',
    'twit twoo',
    'twitter',
    'tzing',
    'uggh',
    'ugh',
    'uh - huh uh - oh',
    'umpa',
    'untz untz untz',
    'varoom',
    'veery',
    'viip',
    'voomp vooRRRR, voo',
    'vreeeeeeeeeeeeeeew',
    'vroo - vroo vroom',
    'vworp',
    'vzzzzt',
    'waaa',
    'waaank',
    'waahhh',
    'waak',
    'waffle',
    'wah - wah',
    'wahh',
    'wahoo',
    'wail',
    'wallop',
    'wap',
    'warble',
    'wee - wee',
    'weeeoooeee',
    'weep',
    'whaam',
    'whack',
    'whallop',
    'wham',
    'whang',
    'whap',
    'Whargharble',
    'whee',
    'wheeze',
    'wher, wher, wher',
    'whew',
    'whi - cha',
    'whiff whimper',
    'whine',
    'whiney',
    'whinny',
    'whip',
    'whip - poor - will',
    'whipbird',
    'whipped',
    'whir',
    'whirl',
    'whirr',
    'whirred',
    'whish',
    'whisper',
    'whispered',
    'whispering',
    'whispers',
    'whistle',
    'whit woo',
    'whiz',
    'whizz',
    'whizz',
    'whizzed',
    'whoa',
    'whock',
    'whockah',
    'whomp',
    'whoo whoop',
    'whooped',
    'whooping cough',
    'whooping crane',
    'whoops',
    'whoosh',
    'whop',
    'whop whop whop',
    'whump',
    'whumpa - whumpa - ',
    'whup - whup - whup',
    'willet',
    'Wink',
    'wizz',
    'wlu - wlu - wlu - ',
    'woah, oh, oh, oh!',
    'woh woh woh woh',
    'woo - hoo!',
    'woo - woo - woo',
    'woof',
    'woofed',
    'woohoo',
    'woops',
    'woosh',
    'wow',
    'wub wub',
    'wuh - uh - uh - uh',
    'wuppa wuppa',
    'yackety - yak',
    'yadda',
    'yadda yadda / yada', '    yahoo',
    'yakyakyakyak',
    'yammer',
    'yank',
    'yap',
    'yap yap',
    'yapping',
    'yar',
    'yawn',
    'yawp yay',
    'YEEeeEEeeEEeeEEeeE',
    'yeeha, yeehaw, yee',
    'yell',
    'yelp',
    'yelped',
    'yeow',
    'yikes',
    'Yikes!',
    'yip',
    'yippee',
    'yodel',
    'yoink',
    'yoink',
    'yoo - hoo',
    'yoooo',
    'yow',
    'yowl',
    'yowt',
    'yucchh',
    'yuck',
    'Yuk',
    'yuk yuk',
    'yummy',
    'zap',
    'zapped',
    'zchunk',
    'zigzag',
    'zing zip',
    'Zip!',
    'zipped',
    'zipper',
    'zlopp zonk',
    'zoom',
    'zoomba - zoom',
    'zoomed',
    'zzzz'
]

function makeOnomatopoeia() {
    let randomOnomatopoeia = onomatopoeia[Math.floor(Math.random() * onomatopoeia.length)];
    console.log(randomOnomatopoeia);
}

makeOnomatopoeia();